//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso_Times {
    
    
    public partial class Default {
        
        /// <summary>
        /// NewsItemsBulletedList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Contoso_Times.NewsItemsBulletedList NewsItemsBulletedList1;
        
        /// <summary>
        /// NewsItemsBulletedList2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Contoso_Times.NewsItemsBulletedList NewsItemsBulletedList2;
        
        /// <summary>
        /// NewsItemsBulletedList3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Contoso_Times.NewsItemsBulletedList NewsItemsBulletedList3;
        
        /// <summary>
        /// NewsItemsBulletedList4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Contoso_Times.NewsItemsBulletedList NewsItemsBulletedList4;
        
        /// <summary>
        /// NewsItemsBulletedList5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Contoso_Times.NewsItemsBulletedList NewsItemsBulletedList5;
        
        /// <summary>
        /// NewsItemsBulletedList6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Contoso_Times.NewsItemsBulletedList NewsItemsBulletedList6;
        
        /// <summary>
        /// LoginView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LoginView LoginView1;
        
        /// <summary>
        /// NewsItemsBulletedList7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Contoso_Times.NewsItemsBulletedList NewsItemsBulletedList7;
        
        /// <summary>
        /// NewsItemsBulletedList8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Contoso_Times.NewsItemsBulletedList NewsItemsBulletedList8;
        
        /// <summary>
        /// NewsItemsBulletedList9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Contoso_Times.NewsItemsBulletedList NewsItemsBulletedList9;
    }
}
